sudo: required
services:
    - docker

before_install:
    - docker build -t rajatverma311201/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rajatverma311201/docker-react npm run test -- --coverage
