name: Docker Image CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build -t rajatverma311201/docker-react -f Dockerfile.dev .

            - name: Run Tests
              run: docker run -e CI=true rajatverma311201/docker-react npm run test -- --coverage
